[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sonic-cipher"
version = "1.0.0"
description = "Spoof-Aware Speaker Verification System"
readme = "README.md"

authors = [
    {name = "Hansini Karunarathne", email = "hansini.20@cse.mrt.ac.lk"},
    {name = "Wathmi Thennakoon", email = "wathmi.20@cse.mrt.ac.lk"},
    {name = "Sulakshi Gunarathne", email = "sulakshi.20@cse.mrt.ac.lk"}
]

maintainers = [
    {name = "Hansini Karunarathne", email = "hansini.20@cse.mrt.ac.lk"},
    {name = "Wathmi Thennakoon", email = "wathmi.20@cse.mrt.ac.lk"},
    {name = "Sulakshi Gunarathne", email = "sulakshi.20@cse.mrt.ac.lk"}
]

license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "joblib==1.5.1",
    "numpy==2.3.1",
    "psycopg2-binary==2.9.10",
    "python-dotenv==1.1.1",
    "soundfile==0.13.1",
    "speechbrain==1.0.3",
    "timm==1.0.15",
    "scikit-learn==1.6.1"   
    # Install Torch and Torchaudio separately
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["sonic_cipher", "ASV_System", "CM_System", "Weights"]
include-package-data = true

[project.urls]
Repository = "https://github.com/SonicCypher/Speaker-Verification-Application.git"

[tool.setuptools.package-data]
"*" = ["*.pth", "*.pkl", "*.json"]